using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Aspid.Generators.Helper;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DescriptionGenerators;

[Generator(LanguageNames.CSharp)]
public class FactoryRegistrationGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Find all AddNew<T>("path") invocations
		var addNewInvocations = context.SyntaxProvider.CreateSyntaxProvider(
			predicate: IsAddNewInvocation,
			transform: GetAddNewData
		).Where(x => x.HasValue).Select((x, _) => x!.Value);

		// Find all classes with DescriptionTypeAttribute
		var descriptionTypes = context.SyntaxProvider.ForAttributeWithMetadataName(
			"Modules.Framework.Core.DescriptionTypeAttribute",
			predicate: (node, _) => node is ClassDeclarationSyntax,
			transform: GetDescriptionTypeData
		).Where(x => x.HasValue).Select((x, _) => x!.Value);

		// Combine and generate
		var combined = addNewInvocations.Collect().Combine(descriptionTypes.Collect());
		
		context.RegisterSourceOutput(combined, GenerateCode);
	}

	private static bool IsAddNewInvocation(SyntaxNode node, CancellationToken ct)
	{
		// Looking for: factory.AddNew<T>("path")
		return node is InvocationExpressionSyntax
		{
			Expression: MemberAccessExpressionSyntax
			{
				Name: GenericNameSyntax { Identifier.Text: "AddNew" }
			}
		};
	}

	private static AddNewData? GetAddNewData(GeneratorSyntaxContext context, CancellationToken ct)
	{
		var invocation = (InvocationExpressionSyntax)context.Node;
		var memberAccess = (MemberAccessExpressionSyntax)invocation.Expression;
		var genericName = (GenericNameSyntax)memberAccess.Name;

		// Get the type argument T from AddNew<T>
		if (genericName.TypeArgumentList.Arguments.Count != 1)
			return null;

		var typeArg = genericName.TypeArgumentList.Arguments[0];
		var typeSymbol = context.SemanticModel.GetTypeInfo(typeArg, ct).Type as INamedTypeSymbol;
		if (typeSymbol == null)
			return null;

		// Get the path string argument
		if (invocation.ArgumentList.Arguments.Count != 1)
			return null;

		var pathArg = invocation.ArgumentList.Arguments[0].Expression;
		var pathValue = context.SemanticModel.GetConstantValue(pathArg, ct);
		if (!pathValue.HasValue || pathValue.Value is not string path)
			return null;

		return new AddNewData(typeSymbol, path);
	}

	private static DescriptionTypeData? GetDescriptionTypeData(GeneratorAttributeSyntaxContext context, CancellationToken ct)
	{
		if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
			return null;

		// Get the type argument from DescriptionTypeAttribute
		var attribute = context.Attributes.FirstOrDefault();
		var typePath = attribute?.ConstructorArguments.FirstOrDefault().Value as string ?? string.Empty;

		return new DescriptionTypeData(typeSymbol, typePath);
	}

	private void GenerateCode(
		SourceProductionContext context,
		(ImmutableArray<AddNewData> AddNewCalls, ImmutableArray<DescriptionTypeData> DescriptionTypes) data)
	{
		// Group description types by their implemented interfaces
		var typesByInterface = new Dictionary<string, List<DescriptionTypeData>>();

		foreach (var descType in data.DescriptionTypes)
		{
			foreach (var iface in descType.typeSymbol.AllInterfaces)
			{
				var ifaceName = iface.ToDisplayString();
				if (!typesByInterface.ContainsKey(ifaceName))
					typesByInterface[ifaceName] = new List<DescriptionTypeData>();
				typesByInterface[ifaceName].Add(descType);
			}
		}

		// Generate extension for each AddNew<T> call
		foreach (var addNew in data.AddNewCalls)
		{
			var interfaceName = addNew.interfaceType.ToDisplayString();
			var interfaceSimpleName = addNew.interfaceType.Name;

			if (!typesByInterface.TryGetValue(interfaceName, out var implementations))
				continue;

			var code = new CodeWriter();
			
			// Generate the extension class
			code.AppendLine("// <auto-generated/>");
			code.AppendLine();
			code.AppendLine($"namespace {addNew.interfaceType.ContainingNamespace.ToDisplayString()}");
			code.BeginBlock();
			
			code.AppendLine($"public static class __{interfaceSimpleName}Extension");
			code.BeginBlock();
			
			code.AppendLine($"public static void RegisterAll(this Framework.Core.Factories.Registration<{interfaceName}> registration)");
			code.BeginBlock();
			
			code.AppendLine("var factory = registration.factory;");
			code.AppendLine();

			foreach (var impl in implementations)
			{
				var typePath = !string.IsNullOrEmpty(impl.typePath) 
					? impl.typePath 
					: ToSnakeCase(impl.typeSymbol.Name);
				
				code.AppendLine($"factory.Add<{interfaceName}>(\"{typePath}\", typeof({impl.typeSymbol.ToDisplayString()}));");
			}

			code.EndBlock(); // RegisterAll
			code.EndBlock(); // class
			code.EndBlock(); // namespace

			context.AddSource($"__{interfaceSimpleName}Extension.g.cs", code.GetSourceText());
		}
	}

	private static string ToSnakeCase(string name)
	{
		if (string.IsNullOrEmpty(name))
			return name;

		var builder = new System.Text.StringBuilder();
		for (int i = 0; i < name.Length; i++)
		{
			var c = name[i];
			if (char.IsUpper(c))
			{
				if (i > 0)
					builder.Append('_');
				builder.Append(char.ToLowerInvariant(c));
			}
			else
			{
				builder.Append(c);
			}
		}
		return builder.ToString();
	}

	private readonly struct AddNewData(INamedTypeSymbol interfaceType, string path)
	{
		public readonly INamedTypeSymbol interfaceType = interfaceType;
		public readonly string path = path;
	}

	private readonly struct DescriptionTypeData(INamedTypeSymbol typeSymbol, string typePath)
	{
		public readonly INamedTypeSymbol typeSymbol = typeSymbol;
		public readonly string typePath = typePath;
	}
}
